# Generated by Django 5.0.2 on 2025-01-29 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0002_remove_question_session_remove_question_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='date_end',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='session',
            name='date_start',
            field=models.IntegerField(),
        ),
    ]
