# Generated by Django 5.0.2 on 2025-01-29 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0003_alter_session_date_end_alter_session_date_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='date_end',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='session',
            name='date_start',
            field=models.CharField(max_length=30),
        ),
    ]
