# Generated by Django 5.0.2 on 2025-01-29 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0005_roommember'),
        ('user', '0005_alter_profile_user_is_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='topic',
            new_name='room_name',
        ),
        migrations.AlterField(
            model_name='session',
            name='author',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='user.profile_user'),
        ),
    ]
